apiVersion: v1
kind: Pod
metadata:
  name: simple-webapp-color-pod
  labels:
    name: simple-webapp-color-pod
spec:
  container:
    - name: simple-webapp-color
      image: simple-webapp-color
      ports:
        - containerPort: 8080
      envFrom:
        - configMapRef:
          name: app-config