apiVersion: v1
kind: Pod
metadata:
  name: simple-app
  labels: simple-app
spec:
  containers:
    - name: simple-app
      image: ubuntu
      ports: 
        - containerPort: 8000
      envFrom:
        - secretRef:
            name: app-secret